import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Componentes/Header";
import Footer from "./Componentes/Footer";
import { MyProvider } from "./Componentes/UseContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-screen">
      <body className="flex flex-col h-screen vsc-initialized">
        <MyProvider>
          <Header />
          <main className="flex-grow">
            <div className="container mx-auto">{children}</div>
          </main>
          <Footer />
        </MyProvider>
      </body>
    </html>
  );
}
